name: Deploy on Azure

on:
  push:

  pull_request:
    types: [opened, reopened, edited, synchronize]

# env:
#   ARTIFACT_LOCATION: "./deploy"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          credentials: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy code to Azure
        run: |
          dotnet tool restore
          dotnet run Azure
      